apiVersion: v1
kind: Pod
metadata: 
  name: build-pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: custom-agent
      image: josiokoko/onyxquity-inbound-agent
      command: ["tail", "-f", "/dev/null"]
      resources: {}
      env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
    # - name: docker-client
    #   image: docker:19.03.1
    #   # command: ['sleep', '99d']
    #   command: ["tail", "-f", "/dev/null"] # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
    #   resources: {}
    #   env:
    #     - name: DOCKER_HOST
    #       value: tcp://localhost:2376
    #     - name: DOCKER_CERT_PATH
    #       value: /certs/client
    #     - name: DOCKER_TLS_VERIFY
    #       value: "1"
    - name: docker-daemon
      image: docker:dind
      resources: {}
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
    # - name: cache
    #   hostPath:
    #     path: /tmp
    #     type: Directory
    # # - name: docker
    # #   hostPath:
    # #     path: /var/run/docker.sock
      